### ISSUE TITLE
Panic!

### ISSUE THREAD

**Issue by JeanMichelleJarre** [HouCoder/asrock-z370m-pro4-hackintosh#8]
Hi. First of all thank you very much for your work. I was trying to migrate from Clover to Opencore with a config very similar to yours (8400, Z370m-pro 4 but with dedicated graphics Intel HD 630).
Clover works perfectly for me but when I switch to Opencore I am not able to fix this KP. Thank you again! Regards.

![IMG_20191121_093405](https://user-images.githubusercontent.com/54317354/69321228-ff5ed000-0c42-11ea-81d9-72e0428538e6.jpg)

**Comment by HouCoder** [comment]
Could you upload your EFI folder to GitHub? it's really hard to read the text on the image.

**Comment by JeanMichelleJarre** [comment]
Hi. Thanks for answering. I was going to answer you but I have seen that you have modified the ACPI folder and the config.plist and I have decided to try it before responding to this.

With this new one that you have uploaded, the PC now restarts when it tries to load. It doesn't give me time to see what the error is or why it restarts. I have entered verbose mode but I fail to see the fault that reboots the PC with your new OC.

Thank you. Regards.

**Comment by HouCoder** [comment]
1. Please read this article for setup details - https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/config.plist/coffee-lake

2. Remember to change `CPU0` in this file accordingly - https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PLUG.dsl

3. Did you set the platform-id correctly? since you only have iGPU, I think the correct platform-id for you should be `07009B3E` https://github.com/corpnewt/Hackintosh-Guide/blob/master/config.plist-per-hardware/coffee-lake.md#properties

**Comment by HouCoder** [comment]
I've updated the config file, my Hackintosh works great now, wish you luck.

**Comment by JeanMichelleJarre** [comment]
Hi! Indeed, as you said, it worked for me by changing platform-id to 07009B3E and, above all, so that there were no glitches or pulls, also changing the SMBios. In my case it worked perfectly with iMac 19.1 (although I also think it would have worked with 19.2).

Thank you for your efforts and your advices. I find this change from Clover to Opencore a bit difficult xD. I had already understood how it was placed and how Clover worked.
